# Generated by Django 3.1.7 on 2021-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cust_id', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=10)),
                ('Amount', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
